ALTER TABLE ddcc RENAME COLUMN var4 TO var6;
ALTER TABLE ddcc ALTER COLUMN var3 SET DEFAULT (0);
ALTER TABLE ddcc ALTER COLUMN var3 DROP NOT NULL;
-- GAS_ORM(forward_backward_separator)
ALTER TABLE ddcc ALTER COLUMN var3 SET DEFAULT (0);
ALTER TABLE ddcc ALTER COLUMN var3 SET NOT NULL;
ALTER TABLE ddcc ALTER COLUMN var3 DROP DEFAULT;
ALTER TABLE ddcc RENAME COLUMN var6 TO var4;
