CREATE TABLE IF NOT EXISTS audit_logs(
	id BIGSERIAL NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	random_date DATE NOT NULL,
	random_time TIME NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS orders(
	id BIGSERIAL NOT NULL,
	quantity INTEGER NOT NULL,
	user_fk BIGINT NOT NULL,
	product_fk BIGINT, 
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS persons(
	id BIGSERIAL NOT NULL,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	phone_number TEXT,
	bank_balance DECIMAL NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS posts(
	id BIGSERIAL NOT NULL,
	title TEXT NOT NULL,
	user_fk BIGINT NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS products(
	id BIGSERIAL NOT NULL,
	name TEXT NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS users(
	id BIGSERIAL NOT NULL,
	name TEXT NOT NULL, 
	PRIMARY KEY (id)
);
-- GAS_ORM(forward_backward_separator)
DROP TABLE audit_logs;
DROP TABLE orders;
DROP TABLE persons;
DROP TABLE posts;
DROP TABLE products;
DROP TABLE users;
