ALTER TABLE ccdd DROP COLUMN var;
ALTER TABLE ccdd ADD COLUMN var TEXT NOT NULL;
ALTER TABLE DROP CONSTRAINT ddcc_var3_fkey;
-- GAS_ORM(forward_backward_separator)
ALTER TABLE ddcc ADD FOREIGN KEY(var3) REFERENCES ccdd(id);
ALTER TABLE ccdd DROP COLUMN var;
ALTER TABLE ccdd ADD COLUMN var INTEGER NOT NULL;
