CREATE TABLE IF NOT EXISTS ccdd(
	id BIGINT NOT NULL,
	var INTEGER NOT NULL, 
	PRIMARY KEY (id)
);
ALTER TABLE ddcc ADD PRIMARY KEY(id);
ALTER TABLE ddcc ALTER COLUMN var2 SET DEFAULT ('');
ALTER TABLE ddcc ALTER COLUMN var2 SET DEFAULT ('');
ALTER TABLE ddcc ALTER COLUMN var2 SET NOT NULL;
ALTER TABLE ddcc ADD UNIQUE(var2);
ALTER TABLE ddcc DROP COLUMN var4;
ALTER TABLE ddcc ADD COLUMN var4 INTEGER NOT NULL;
ALTER TABLE ddcc ADD FOREIGN KEY(var3) REFERENCES ccdd(id);
-- GAS_ORM(forward_backward_separator)
ALTER TABLE DROP CONSTRAINT ddcc_var3_fkey;
ALTER TABLE ddcc DROP COLUMN var4;
ALTER TABLE ddcc ADD COLUMN var4 BIGINT NOT NULL;
ALTER TABLE ddcc DROP CONSTRAINT var2_unq;
ALTER TABLE ddcc ALTER COLUMN var2 DROP NOT NULL;
ALTER TABLE ddcc ALTER COLUMN var2 DROP DEFAULT;
ALTER TABLE ddcc DROP CONSTRAINT ddcc_pkey;
DROP TABLE ccdd;
