ALTER TABLE ccdd ADD COLUMN var2 TEXT NOT NULL UNIQUE;
ALTER TABLE ccdd ADD UNIQUE(var);
ALTER TABLE ddcc DROP COLUMN var1;
ALTER TABLE ddcc ADD COLUMN var1 BIGINT NOT NULL;
-- GAS_ORM(forward_backward_separator)
ALTER TABLE ddcc DROP COLUMN var1;
ALTER TABLE ddcc ADD COLUMN var1 TEXT NOT NULL UNIQUE;
ALTER TABLE ccdd DROP CONSTRAINT ccdd_var_key;
ALTER TABLE ccdd DROP COLUMN var2;
