ALTER TABLE ddcc DROP COLUMN var4;
ALTER TABLE ddcc ADD COLUMN var4 TEXT NOT NULL;
-- GAS_ORM(forward_backward_separator)
ALTER TABLE ddcc DROP COLUMN var4;
ALTER TABLE ddcc ADD COLUMN var4 INTEGER NOT NULL;
